<?php
$metadata["Tasks"]["Edit"]=array(
    "hidden"=>array(
        "status"
    ),
    "panels"=>array(
        array(
            "name",
            "email"
        ),
        array(
            "description"
        )
    )
);